/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.cbook.view;

import ec.edu.espe.cbook.model.ModifyProduct;
import ec.edu.espe.cbook.model.ModifySale;
import ec.edu.espe.cbook.model.RegisterSale;
import ec.edu.espe.cbook.model.SaleUpload;

/**
 *
 * @author Kerly
 */
public class FrmInventoryStart extends javax.swing.JFrame {

    /**
     * Creates new form FrmInventoryStart
     */
    public FrmInventoryStart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ItmProductSold = new javax.swing.JMenuItem();
        ItmProduct = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ItmModifySale = new javax.swing.JMenuItem();
        ItmModifyProduct = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        ItmShowProduct = new javax.swing.JMenuItem();
        ItmShowSales = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("WELCOME TO INVENTORY TIRE STORE ");

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Add");

        ItmProductSold.setText("Products Sold");
        ItmProductSold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmProductSoldActionPerformed(evt);
            }
        });
        jMenu1.add(ItmProductSold);

        ItmProduct.setText("  Products");
        ItmProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmProductActionPerformed(evt);
            }
        });
        jMenu1.add(ItmProduct);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Modify");

        ItmModifySale.setText("Sale");
        ItmModifySale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmModifySaleActionPerformed(evt);
            }
        });
        jMenu2.add(ItmModifySale);

        ItmModifyProduct.setText("Product");
        ItmModifyProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmModifyProductActionPerformed(evt);
            }
        });
        jMenu2.add(ItmModifyProduct);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Show");

        ItmShowProduct.setText("Products");
        ItmShowProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmShowProductActionPerformed(evt);
            }
        });
        jMenu4.add(ItmShowProduct);

        ItmShowSales.setText("Sales");
        ItmShowSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmShowSalesActionPerformed(evt);
            }
        });
        jMenu4.add(ItmShowSales);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItmProductSoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmProductSoldActionPerformed
        RegisterSale frmReservation =new RegisterSale();
        frmReservation.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ItmProductSoldActionPerformed

    private void ItmProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmProductActionPerformed
        FrmInventory frmProduct =new FrmInventory();
        frmProduct.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ItmProductActionPerformed

    private void ItmModifySaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmModifySaleActionPerformed
        
    }//GEN-LAST:event_ItmModifySaleActionPerformed

    private void ItmModifyProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmModifyProductActionPerformed
        
    }//GEN-LAST:event_ItmModifyProductActionPerformed

    private void ItmShowProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmShowProductActionPerformed
        ModifyProduct frmProduct =new ModifyProduct();
        frmProduct.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ItmShowProductActionPerformed

    private void ItmShowSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmShowSalesActionPerformed
        ModifySale frmProduct =new ModifySale();
        frmProduct.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ItmShowSalesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInventoryStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInventoryStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInventoryStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInventoryStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInventoryStart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItmModifyProduct;
    private javax.swing.JMenuItem ItmModifySale;
    private javax.swing.JMenuItem ItmProduct;
    private javax.swing.JMenuItem ItmProductSold;
    private javax.swing.JMenuItem ItmShowProduct;
    private javax.swing.JMenuItem ItmShowSales;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
